apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels: # Ajoutez cette section
    app: site-doc # Ce label correspondra au s√©lecteur du service
spec:
  containers:
  - name: site
    image: valouze14/valouze14:latest
    ports:
    - containerPort: 8080
    - containerPort: 4443